matches:
  # --- keep tddh ---
  - trigger: ":tddh"
    replace: >-
      Think Deeply. Don't Hallucinate.

  # --- New Task (API): create Todoist task via external script ---
  - trigger: ":ntsk"
    replace: "{{create_todoist_task_ntsk}}"
    vars:
      - name: ntsk
        type: form
        params:
          layout: |-
            Action - Verb + Object + Action: [[action]]
            DoD - Falsifiable: [[dod]]
            Next Right Action: [[nra]]
            TYPE (e.g., research, bug, feature): [[type]]
          fields:
            type:
              multiline: false
            action:
              multiline: false
            dod:
              multiline: false
            nra:
              multiline: false

      - name: create_todoist_task_ntsk
        type: shell
        params:
          # Windows PowerShell via CMD; hardcoded UNC path to repo script for reliability.
          cmd: >-
            cmd /C powershell -NoProfile -ExecutionPolicy Bypass -Command
            "$p=$env:PROMPT_AUTOMATION_REPO;
            if ($p) { $p=Join-Path $p 'scripts\todoist_add.ps1' }
            else {
              $p='\\wsl$\Ubuntu\home\josiah\github-cf\prompt-automation\scripts\todoist_add.ps1';
              if (-not (Test-Path $p)) { $p='\\wsl.localhost\Ubuntu\home\josiah\github-cf\prompt-automation\scripts\todoist_add.ps1' }
            };
            if (-not (Test-Path $p)) { Write-Error ('Script not found: ' + $p); exit 1 };
            powershell -NoProfile -ExecutionPolicy Bypass -File $p '{{ntsk.type}} - {{ntsk.action}} — DoD: {{ntsk.dod}}' 'NRA: {{ntsk.nra}}'"

  # --- Communication coach prompt (asks for 3 inputs, prints two options only) ---
  - trigger: ":comms"
    replace: |-
      You are an expert communication coach.

      Variables:
      - Message (rough sketch, expand and clarify): {{comms.message}}
      - Audience: {{comms.audience}}
      - Tone (two adjectives): {{comms.tone}}

      Produce exactly two versions of the same communication and nothing else:
      1) Concise version - direct, clear, outcome-oriented.
      2) Elaborate version - slightly more detailed, still crisp; add necessary context or reasoning.

      Apply these rules rigorously:
      - Keep it simple; make every word count. Remove filler, buzzwords, and needless qualifiers.
      - Write conversationally; use everyday language and contractions.
      - Put the audience first: emphasize benefits, outcomes, and next steps for them.
      - Don't overwhelm; include only what's needed to decide or act.
      - Be approachable, confident, and optimistic; avoid fear-mongering.
      - Use active voice; lead with actions and results.
      - Use sentence case; avoid title case. One space after periods.
      - Prefer short sentences and short paragraphs.
      - Avoid greetings and preambles (e.g., "Hi team," "Hope you're well") unless explicitly requested.
      - Use bullets for scanning when it improves clarity; keep bullets parallel and brief.
      - Write out acronyms on first mention; minimize abbreviations.
      - Use the serial (Oxford) comma.
      - Hyphenate only when needed for clarity; don't hyphenate -ly adverbs.
      - Numbers: spell out zero to nine; use numerals for 10+ and for % and $.
      - Be specific about the desired action, owner, and timing.

      Constraints:
      - No salutations or sign-offs unless the prompt explicitly asks for them.
      - No meta commentary or preambles - output only the two versions.

      Format:
      Option 1 - concise:
      [write the concise version here]

      Option 2 - elaborate:
      [write the slightly more detailed version here]
    vars:
      - name: comms
        type: form
        params:
          layout: |-
            Message (rough sketch): [[message]]
            Audience (e.g., manager, client) - multi-line allowed: [[audience]]
            Tone (two adjectives, comma-separated; avoid double braces): [[tone]]
          fields:
            message:
              multiline: true
            audience:
              multiline: true
            tone:
              multiline: false
