name: Espanso Package CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML presence
        run: |
          test -f espanso-package/_manifest.yml
          test -f espanso-package/package.yml
          test -d espanso-package/match
name: Espanso Package CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:
    inputs:
      new_version:
        description: "New espanso package version (semver)"
        required: false
        type: string

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pyyaml

      - name: Run espanso package tests only
        run: pytest -q tests/espanso

  release:
    if: ${{ inputs.new_version != '' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyYAML
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Bump espanso package version in _manifest.yml
        run: |
          python - << 'PY'
          import sys, yaml, pathlib
          root = pathlib.Path('.').resolve()
          path = root / 'espanso-package' / '_manifest.yml'
          data = yaml.safe_load(path.read_text())
          data['version'] = '${{ inputs.new_version }}'
          path.write_text(yaml.safe_dump(data, sort_keys=False))
          print(f"Bumped version to {data['version']} in {path}")
          PY

      - name: Commit changes and tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add espanso-package/_manifest.yml
          git commit -m "chore(espanso): release ${{ inputs.new_version }}"
          git tag -a "espanso-v${{ inputs.new_version }}" -m "Espanso package ${{ inputs.new_version }}"
          git push --follow-tags
