name: Publish to PyPI

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build wheel and sdist
        run: |
          python -m build
          ls -l dist

      - name: Publish to PyPI (twine)
        id: twine_upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "Uploading distributions to PyPI via twine"
          python -m twine upload --skip-existing dist/*

      - name: Retry upload (network transient workaround)
        if: failure() && steps.twine_upload.outcome == 'failure'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "First upload attempt failed; waiting 10s and retrying..."
          sleep 10
          python -m twine upload --skip-existing dist/* || echo "Retry failed"

      - name: Show package metadata
        run: |
          python -m pip install --no-deps dist/*.whl
          python -c "
          import importlib.metadata as m
          print('Installed version:', m.version('prompt-automation'))
          "
