name: Publish to PyPI

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build wheel and sdist
        run: |
          python -m build
          ls -l dist

      - name: Publish to PyPI
        if: success()
        uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          verbose: true

      - name: Show package metadata
        run: |
          python -m pip install --no-deps dist/*.whl
          python -c "
          import importlib.metadata as m
          print('Installed version:', m.version('prompt-automation'))
          "
